version: '3.3'

services:
  backend:
    build: ./backend
    networks:
    - my-network
    depends_on: 
    - database

  database:
    build: ./database
    networks:
    - my-network

  httpd:
    build: ./http
    ports: 
    - "80:80"
    networks:
    - my-network
    - my_network2
    depends_on: 
    - backend
  
  front:
    build: ./front
    networks:
    - my_network2
    depends_on: 
    - httpd

networks:
  my-network:
  my_network2: